[package]
name = "stm32test"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7"
cortex-m-rtic = "1"
defmt = "0.3"
defmt-rtt = "0.4"
embedded-hal = "0.2"
panic-probe = "0.3"
stm32f4xx-hal = {version = "0.18", features = ["stm32f469", "defmt", "rt", "rtic"]}
systick-monotonic = "1"
